### ISSUE TITLE
字符转换为问号

### ISSUE THREAD

**Issue by AlexanderHel** [findsky6544/qidianContentExtract#1]
有什么办法可以修复这个错误吗？

![image](https://github.com/findsky6544/qidianContentExtract/assets/99399435/1b3dfa00-6706-414b-b104-4dc2a43e9d2d)

**Comment by findsky6544** [comment]
我自己这边测试是没问题的，感觉像是编码问题。改一下notepad++的编码试试呢

**Comment by AlexanderHel** [comment]
我尝试更改记事本++中的编码但仍然不起作用

另外还有一个bug，下载的章节没有完成。

这是一个视频来演示


https://github.com/findsky6544/qidianContentExtract/assets/99399435/73b5a02b-9f94-464f-bcf2-20ab28dba6a1

**Comment by AlexanderHel** [comment]
4.1版本仍然存在相同字符的bug
![image](https://github.com/findsky6544/qidianContentExtract/assets/99399435/14da8f4e-3dbb-4d4b-b760-a98892178d4b)

**Comment by AlexanderHel** [comment]
对于那个很抱歉

对区域设置进行一些调整后，我能够修复该错误，非常感谢

**Comment by findsky6544** [comment]
我看了一下，我默认的输出应该是和电脑的编码有关，我在记事本中打开并另存为时显示为ANSI编码。确实可能和电脑的区域有关。最新版将尝试默认使用utf-8输出，也许可以解决

**Comment by AlexanderHel** [comment]
是的，最新版本修复了这个bug

文本文件中的所有字符均正确显示

非常感谢
